"""initial schema

Revision ID: 7bb2ed54bd4d
Revises: 
Create Date: 2026-07-15 12:43:47.105115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bb2ed54bd4d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=True),
    sa.Column('auth_type', sa.Enum('api_key', 'none', 'local', name='authtype', native_enum=False), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('cooling_down_until', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_providers_name'), 'providers', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('used_by_user_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['used_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invites_code'), 'invites', ['code'], unique=True)
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(length=50), nullable=False),
    sa.Column('model_id', sa.String(length=150), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=False),
    sa.Column('supports_vision', sa.Boolean(), nullable=False),
    sa.Column('supports_coding_hint', sa.Integer(), nullable=True),
    sa.Column('supports_reasoning_hint', sa.Integer(), nullable=True),
    sa.Column('context_length', sa.Integer(), nullable=True),
    sa.Column('speed_rating', sa.Integer(), nullable=True),
    sa.Column('free', sa.Boolean(), nullable=False),
    sa.Column('quality_source', sa.Enum('benchmarked', 'curated', 'unrated', name='qualitysource', native_enum=False), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['provider_name'], ['providers.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_name', 'model_id', name='uq_model_provider_modelid')
    )
    op.create_table('provider_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('provider_name', sa.String(length=50), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('encrypted_key', sa.String(), nullable=False),
    sa.Column('is_shared', sa.Boolean(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('daily_usage_count', sa.Integer(), nullable=False),
    sa.Column('daily_usage_reset_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('health_status', sa.Enum('green', 'yellow', 'red', name='healthstatus', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'invalid_key', 'revoked', name='providerkeystatus', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['provider_name'], ['providers.name'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quota_usages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('provider_name', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('daily_limit', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider_name', 'date', name='uq_quota_user_provider_date')
    )
    op.create_table('request_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(length=50), nullable=False),
    sa.Column('model_id', sa.String(length=150), nullable=False),
    sa.Column('endpoint', sa.String(length=100), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('fallback_count', sa.Integer(), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_logs_trace_id'), 'request_logs', ['trace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_logs_trace_id'), table_name='request_logs')
    op.drop_table('request_logs')
    op.drop_table('quota_usages')
    op.drop_table('provider_keys')
    op.drop_table('models')
    op.drop_index(op.f('ix_invites_code'), table_name='invites')
    op.drop_table('invites')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_providers_name'), table_name='providers')
    op.drop_table('providers')
    # ### end Alembic commands ###
